CREATE TABLE heart_attack_ger (
	State text,
	Age_Group text,
	Heart_Attack_Incidence int,
	Year int,
	Gender text,
	BMI numeric,
	Smoking_Status text,
	Alchol_Consumption numeric,
	Physical_Activity_Level text,
	Diet_Quality text,
	Family_History int,
	Hypertension int,
	Cholesterol_Level numeric,
	Diabetes int,
	Urban_Rural text,
	Socioeconomic_Status text,
	Air_Pollution_Index numeric,
	Stress_Level text,
	Healthcare_Access text,
	Education_Level text,
	Employment_Status text,
	Region_Heart_Attack_Rate numeric
)